logLevel: info
remindWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=7b50e0c4-8a35-4f29-b652-25e1d6142c2b"
captchaWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=7b50e0c4-8a35-4f29-b652-25e1d6142c2b"
newTicketWebhookUrl: ""
parts:
  - name: "吴舒汀"
    phone: "17611213883"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=5922d5fa-9d25-4fdd-9a20-3208b6d5c21b"
#  - name: "杨慧"
#    phone: "15048008804"
#    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=97e6c3ae-870f-4907-b797-3394f014927e"
#  - name: "冯浪"
#    phone: "13231010331"
#    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=edeef6e0-b990-4d1b-bdd3-4e81bdf23fa4"
#  - name: "孙嘉彤"
#    phone: "13630909558"
#    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=0b6ab4c4-fc8c-4c51-9f72-50d96c845fba"
#  - name: "李晓升"
#    phone: "17600642139"
#    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=4e9b2363-dc37-4ab4-aeea-d0cab43e5e6c"
#  - name: "霍佳琦"
#    phone: "18812012367"
#    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=de036cd3-a5f4-4aed-ad85-a2799f0c17df"
#  - name: "李斌"
#    phone: "15011332744"
#    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=80d238d4-5e03-4e46-a21e-dcffaaa05637"
  - name: "罗舒文"
    phone: "15177006671"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=1d7438f4-8712-4961-81c2-0c6d0effb408"
  - name: "谭嘉威"
    phone: "15677955548"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=5ab95531-fcdc-4bdb-85a6-115904bf98c7"
#  - name: "孙凯"
#    phone: "13052363610"
#    replyWebhookUrl: ""
#  - name: "杨学成"
#    phone: "13760347163"
#    replyWebhookUrl: ""
  - name: "王硕"
    phone: "18511280705"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=1fa33251-f328-4888-87df-06963cf43065"
#  - name: "崔星林"
#    phone: "17717757039"
#    replyWebhookUrl: ""
  - name: "王奥"
    phone: "15650708414"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=960b4659-e236-468f-b630-a6c138b8105c"
  - name: "王培伦"
    phone: "15874035678"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=3207d9fa-fcf6-4f0d-bfb5-40c4a203688d"
  - name: "王杭渝"
    phone: "17858226798"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=d15f811b-7b33-4bf1-9af9-1d66f833c078"